**Import Modules**

In [1]:
import pandas as pd
import numpy as np

**Import Libraries**

In [5]:
df= pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Credit%20Default.csv')
df.head()

Income        Age         Loan  Loan to Income  Default
0  66155.92510  59.017015  8106.532131        0.122537        0
1  34415.15397  48.117153  6564.745018        0.190752        0
2  57317.17006  63.108049  8020.953296        0.139940        0
3  42709.53420  45.751972  6103.642260        0.142911        0
4  66952.68885  18.584336  8770.099235        0.130990        1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Income          2000 non-null   float64
 1   Age             2000 non-null   float64
 2   Loan            2000 non-null   float64
 3   Loan to Income  2000 non-null   float64
 4   Default         2000 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 78.2 KB


In [7]:
df.describe()

Income          Age          Loan  Loan to Income      Default
count   2000.000000  2000.000000   2000.000000     2000.000000  2000.000000
mean   45331.600018    40.927143   4444.369695        0.098403     0.141500
std    14326.327119    13.262450   3045.410024        0.057620     0.348624
min    20014.489470    18.055189      1.377630        0.000049     0.000000
25%    32796.459720    29.062492   1939.708847        0.047903     0.000000
50%    45789.117310    41.382673   3974.719418        0.099437     0.000000
75%    57791.281670    52.596993   6432.410625        0.147585     0.000000
max    69995.685580    63.971796  13766.051240        0.199938     1.000000

In [9]:
df.shape

(2000, 5)

In [10]:
df['Default'].value_counts()

Default
0    1717
1     283
Name: count, dtype: int64

**Define Y Target & X features**

In [11]:
df.columns

Index(['Income', 'Age', 'Loan', 'Loan to Income', 'Default'], dtype='object')

In [12]:
y= df['Default']
X= df.drop(['Default' ], axis=1)

**Train Test Split**

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, random_state= 2529, test_size=0.2)

**Model Selection**

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
model= LogisticRegression()

In [17]:
model.fit(X_train, y_train)

LogisticRegression()

In [19]:
model.intercept_

array([-0.00068221])

In [20]:
model.coef_

array([[-5.78014803e-05, -1.32895145e-01,  8.92153308e-04,
        -8.19443114e-05]])

In [18]:
y_pred =model.predict(X_test)

In [23]:
accuracy_score(y_test, y_pred)

0.9125

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       347
           1       0.78      0.47      0.59        53

    accuracy                           0.91       400
   macro avg       0.85      0.73      0.77       400
weighted avg       0.91      0.91      0.90       400



In [27]:
confusion_matrix(y_test,y_pred)

array([[340,   7],
       [ 28,  25]])