In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
df= pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/House%20Prices.csv')

In [11]:
df.head()

ID             Date     Price  Bedrooms  Bathrooms  Sqft_living  Sqft_lot  \
0   1  20140916T000000  280000.0         6       3.00         2400      9373   
1   2  20150422T000000  300000.0         6       3.00         2400      9373   
2   3  20140508T000000  647500.0         4       1.75         2060     26036   
3   4  20140811T000000  400000.0         3       1.00         1460     43000   
4   5  20150401T000000  235000.0         3       1.00         1430      7599   

   Floors  Waterfront  View  ...  Grade  Sqft_above  Sqft_basement  Yr_built  \
0     2.0           0     0  ...      7        2400              0      1991   
1     2.0           0     0  ...      7        2400              0      1991   
2     1.0           0     0  ...      8        1160            900      1947   
3     1.0           0     0  ...      7        1460              0      1952   
4     1.5           0     0  ...      6        1010            420      1930   

   Yr_renovated  zipcode      Lat     Long  Sqft_living15  Sqft_lot15  
0             0    98002  47.3262 -122.214           2060        7316  
1             0    98002  47.3262 -122.214           2060        7316  
2             0    98166  47.4444 -122.351           2590       21891  
3             0    98166  47.4434 -122.347           2250       20023  
4             0    98168  47.4783 -122.265           1290       10320  

[5 rows x 21 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   ID             21613 non-null  int64  
 1   Date           21613 non-null  object 
 2   Price          21613 non-null  float64
 3   Bedrooms       21613 non-null  int64  
 4   Bathrooms      21613 non-null  float64
 5   Sqft_living    21613 non-null  int64  
 6   Sqft_lot       21613 non-null  int64  
 7   Floors         21613 non-null  float64
 8   Waterfront     21613 non-null  int64  
 9   View           21613 non-null  int64  
 10  Condition      21613 non-null  int64  
 11  Grade          21613 non-null  int64  
 12  Sqft_above     21613 non-null  int64  
 13  Sqft_basement  21613 non-null  int64  
 14  Yr_built       21613 non-null  int64  
 15  Yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  Lat            21613 non-null  float64
 18  Long  

In [13]:
df.columns

Index(['ID', 'Date', 'Price', 'Bedrooms', 'Bathrooms', 'Sqft_living',
       'Sqft_lot', 'Floors', 'Waterfront', 'View', 'Condition', 'Grade',
       'Sqft_above', 'Sqft_basement', 'Yr_built', 'Yr_renovated', 'zipcode',
       'Lat', 'Long', 'Sqft_living15', 'Sqft_lot15'],
      dtype='object')

In [14]:
y=df['Price']
X=df[['Bedrooms', 'Bathrooms', 'Sqft_living',
       'Sqft_lot', 'Floors', 'Waterfront', 'View', 'Condition', 'Grade',
       'Sqft_above', 'Sqft_basement', 'Yr_built', 'Yr_renovated', 'zipcode',
       'Lat', 'Long', 'Sqft_living15', 'Sqft_lot15']]

**Split the data**

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, random_state=2529)

In [46]:
from sklearn.preprocessing import StandardScaler
ss= StandardScaler()

In [47]:
ss.fit(X_train)

StandardScaler()

In [49]:
X_train= ss.transform(X_train)
X_test= ss.transform(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [50]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [51]:
lr= LinearRegression()
lasso= Lasso(alpha=100, max_iter=5000)
ridge= Ridge(alpha=100, max_iter=5000)

In [52]:
lr.fit(X_train, y_train)

LinearRegression()

In [53]:
lasso.fit(X_train, y_train)

Lasso(alpha=100, max_iter=5000)

In [54]:
ridge.fit(X_train, y_train)

Ridge(alpha=100, max_iter=5000)

In [55]:
lr.coef_

array([-2.82517779e+04,  2.20951082e+04,  6.24295555e+07,  2.52939602e+08,
        3.44259379e+03,  4.76752878e+03,  2.95906124e+04,  1.06709311e+04,
        1.33353623e+05,  7.27155878e+07,  1.45869621e+07, -2.28141448e+06,
        3.50845682e+06, -1.63893072e+06,  1.14574355e+04, -4.07715928e+03,
        1.07286054e+07, -2.72563628e+08])

In [56]:
lasso.coef_

array([ 5.58182321e+03,  6.74137452e+04,  0.00000000e+00,  0.00000000e+00,
        1.85242986e+03,  5.02357789e+03,  3.80014880e+04,  9.81200992e+03,
        2.35371522e+05,  0.00000000e+00,  0.00000000e+00, -2.85859631e+06,
        0.00000000e+00, -1.22430740e+06,  1.08703398e+04, -7.96602688e+02,
        0.00000000e+00,  0.00000000e+00])

In [57]:
ridge.coef_

array([ 1.50089404e+04,  4.93995900e+04,  7.95935817e+03,  5.22334918e+01,
       -9.19123103e+03,  5.13742284e+03,  4.45951365e+04,  2.25655140e+04,
        2.18585311e+05,  7.82035193e+03,  7.00927461e+03, -2.42767536e+05,
        1.04675325e+04, -3.93084873e+04,  1.21412818e+04, -2.26593496e+03,
        7.16581311e+03,  5.54478180e+01])