In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [27]:
from sklearn.preprocessing import StandardScaler

**Load Dataset**

In [28]:
df= pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv')

In [29]:
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [30]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [31]:
y= df['diabetes']
X= df[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]

In [32]:
X_train, X_test,y_train, y_test= train_test_split(X,y, random_state=2529)

In [34]:
ss= StandardScaler()
ss.fit(X_train)
X_train= ss.transform(X_train)
X_test= ss.transform(X_test)

In [35]:
X_train

array([[-0.86122026, -0.4012767 , -0.42871487, ...,  0.45402246,
        -0.16433707, -0.80291   ],
       [ 1.72993808,  0.04358105,  0.467799  , ..., -0.59024756,
         0.14109306,  1.00296567],
       [ 0.86621863, -1.19566554,  0.467799  , ..., -0.36553123,
         0.94402794,  0.22901895],
       ...,
       [-0.28540729,  2.29964536,  0.06934839, ...,  0.37471081,
        -0.71222204, -0.71691592],
       [-0.86122026, -1.06856332, -0.03026426, ...,  0.73161323,
        -0.20841976, -0.80291   ],
       [-0.28540729, -1.89472772,  0.6670243 , ...,  0.30861778,
        -0.70592451,  1.08895975]])

**Create Model**

In [36]:
knn= KNeighborsClassifier()

In [37]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [38]:
y_pred= knn.predict(X_test)

In [39]:
y_pred

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

**Evaluation**

In [40]:
confusion_matrix(y_test,y_pred)

array([[99, 19],
       [41, 33]])

In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.84      0.77       118
           1       0.63      0.45      0.52        74

    accuracy                           0.69       192
   macro avg       0.67      0.64      0.65       192
weighted avg       0.68      0.69      0.67       192



In [42]:
(99+33)/192

0.6875

**Hence accuracy is only 69 %**